[package]
authors = ["Johan Helsing <johanhelsing@gmail.com>"]
categories = ["game-development"]
description = "A camera that allows panning by dragging with the mouse"
edition = "2021"
keywords = ["gamedev", "bevy"]
license = "MIT OR Apache-2.0"
name = "bevy_pancam"
repository = "https://github.com/johanhelsing/bevy_pancam"
version = "0.15.0"

[features]
bevy_egui = ["dep:bevy_egui"]

[dependencies]
bevy = {version = "0.15.0-rc.3", features = ["bevy_render"], default-features = false}
bevy_egui = {git = "https://github.com/mvlabat/bevy_egui", rev = "refs/pull/309/head", optional = true, default-features = false}

[dev-dependencies]
bevy = {version = "0.15.0-rc.3", default-features = false, features = [
  "bevy_render",
  "bevy_asset",
  "bevy_sprite",
  "bevy_winit",
  "bevy_core_pipeline",
  "x11", # github actions runners don't have libxkbcommon installed, so can't use wayland
]}
bevy-inspector-egui = { git = "https://github.com/jakobhellermann/bevy-inspector-egui", rev = "refs/pull/221/head", default-features = false, features = ["bevy_render"]}
bevy_egui = {git = "https://github.com/mvlabat/bevy_egui", rev = "refs/pull/309/head", default-features = false}
rand = "0.8"

[[example]]
name = "egui"
required-features = ["bevy_egui"]

[[example]]
name = "inspector"
required-features = ["bevy_egui"]
